### ISSUE TITLE
Support multiple rooftops ?

### ISSUE THREAD

**Issue by B-Hartley** [dannerph/homeassistant-solcast#13]
As SolCast are stopping tuning, they are offering up to two rooftops per accounts to allow for split arrays.
How difficult would it be for your component to take two RoofTop IDs, get forecasts for both and add them together?

Or to allow you component to be setup twice with different info, I could then add it together myself.

Thanks,
Bruce.

**Comment by dannerph** [comment]
Hi Bruce,
from software architecture view I would go with the second solution, as some of the users might have two completelly different PV system to be observed.
I guess the API limit is valid for both RoofTops, that might need some refactoring of the code ...

I am currently busy with a wast colleaction schedule integration, thus do not have time for the solcast integration right now.

**Comment by B-Hartley** [comment]
No problem. So can two sessions of your integration be added in it’s current form. 
could I make copies of it and change one to solcast2 or something.

**Comment by B-Hartley** [comment]
As a temporary fix, I've made a copy of thecustom component under the domain "solcastx"  and that way I can run two separate instances and add them together.
If anyone else wants to do that and needs a hand, let me know.

**Comment by nonlinearsugar** [comment]
These instructions were helpful in creating a duplicate component: https://community.home-assistant.io/t/how-can-i-create-a-custom-component-by-copying-another/120455

**Comment by B-Hartley** [comment]
Yes, that's pretty much what I did.  Thanks

**Comment by monkeydust** [comment]
thanks for this - worked for me

**Comment by nonlinearsugar** [comment]
This was the template sensor I created to combine the two separate estimates, and the gauge.  Does anyone know how to include the "Tomorrow" and "The day after tomorrow" attributes?


```
#Add to configuration.yaml
sensor:
  - platform: template
    sensors:
      solcast_forecast_total:
        friendly_name: "Solcast Forecast - Total"
        value_template: "{{ states('sensor.solcast_forecast') | float + states('sensor.solcast_forecast_2') | float }}"
        unit_of_measurement: "kWh"
        unique_id: "FpE8m3GmgBsQ"


#Add to Dashboard
type: sensor
entity: sensor.solcast_forecast_total
graph: line
```

**Comment by B-Hartley** [comment]
It would be........

```
sensor:
  - platform: template
    sensors:
      solcast_forecast_tomorrow_total:
        friendly_name: "Solcast Forecast Tomorrow - Total"
        value_template: "{{ state_attr('sensor.solcast_forecast','Tomorrow') | float + state_attr('sensor.solcast_forecast_2','Tomorrow') | float }}"
        unit_of_measurement: "kWh"
        unique_id: "xxxxxxxxxxxxx"
```
