### ISSUE TITLE
Blueprint to push updates/history 

### ISSUE THREAD

**Issue by elRadix** [dannerph/homeassistant-solcast#6]
Can you please create a blueprint automation to facilite the way to push updates/history as the current instructions is really not clear at least for me. This would help also a lot of new users.

Thank your for thinking about it.

**Comment by B-Hartley** [comment]
I did it like this, probably overly complex, but it worked.

```
automation:
  - id: solcast_push_measurement
    alias: "Solcast Push Measurement"
    trigger:
      platform: time_pattern
      minutes: "/30"
    action:
      - choose:
            # Average Power less than 10kWh and Last Meter Was stored between 29 and 31 mins  
          - conditions: >
              {{ ((states('sensor.solaredge_lifetime_production') | float -  states('input_number.solar_meter_30_mins_ago') | float) * 12.0 < 10.0) and
              ((as_timestamp(now())-state_attr('input_datetime.solar_meter_last_stored_data', 'timestamp')) < 1860)  and
              ((as_timestamp(now())-state_attr('input_datetime.solar_meter_last_stored_data', 'timestamp')) > 1740)   }}
            sequence:
              - service: solcast.push_measurement
                data:
                  total_power: "{{ (((states('sensor.solaredge_lifetime_production') | float) -  (states('input_number.solar_meter_30_mins_ago') | float)) * 2.0) | round(2) }}"        
                  period: 'PT30M'
                  period_end: "{{ utcnow() |  replace(' ','T') }}"    
              - service: input_number.set_value
                data:
                  entity_id: input_number.solar_meter_30_mins_ago
                  value: "{{ states('sensor.solaredge_lifetime_production') }}"
              - service: input_datetime.set_datetime
                data:
                  entity_id: input_datetime.solar_meter_last_stored_data
                  datetime: "{{ now() }}"
        default:
          - service: input_number.set_value
            data:
              entity_id: input_number.solar_meter_30_mins_ago
              value: "{{ states('sensor.solaredge_lifetime_production') }}"        
          - service: input_datetime.set_datetime
            data:
              entity_id: input_datetime.solar_meter_last_stored_data
              datetime: "{{ now() }}"
```

I've now switched to doing an overnight batch outside of home assistant.
I download the day from Solaredge, reformat it and upload it to Solcat.
